apiVersion: batch/v1
kind: Job
metadata:
  name: training-validation-job
spec:
  parallelism: 5
  completions: 5
  template:
    spec:
      volumes:
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: persistent-volume-claim-data
      containers:
        - name: training-validation-container
          image: pegaz13/py-env-v:latest
          command: ["python", "/app/train.py"]
          env:
            - name: data_path
              value: "/home/lazark/V/HousingData.csv"
            - name: col_name
              value: "MEDV"
          volumeMounts:
            - name: dataset-volume
              mountPath: "/home/lazark/V"
              readOnly: true
      restartPolicy: Never
  backoffLimit: 4