apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi