version: '3.4'
networks:
  dev:
    driver: bridge
services:
  app-demo:
    image: docker.io/library/todoapi
    depends_on:
     - "app_db"
    container_name: todoapi-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=app_db;Port=5432;Database=TodoDb;Username=postgres;Password=tesseract;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tesseract
      - POSTGRES_DB=TodoDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: